<?php
   header('content-type: text/css');
   /*
   ob_start('ob_gzhandler');
   header('Cache-Control: max-age=31536000, must-revalidate');
   */
?>

<?php
	$colorCodes = array (
		'red' => '#ed1c24',
		'green' => '#228b22',
		'blue' => '#1e90ff',
		'yellow' => '#ffff00',
		'pink' => '#ff1493',
		'orange' => '#f7941d',
		'youtube' => '#df2825'
	);

?>

/* Generated by Font Squirrel (http://www.fontsquirrel.com) on March 11, 2014 */
@font-face {
    font-family: 'papyrusregular';
    src: url('polices/papyrus-webfont.eot');
    src: url('polices/papyrus-webfont.eot?#iefix') format('embedded-opentype'),
         url('polices/papyrus-webfont.woff') format('woff'),
         url('polices/papyrus-webfont.ttf') format('truetype'),
         url('polices/papyrus-webfont.svg#papyrusregular') format('svg');
    font-weight: normal;
    font-style: normal;
}

a
{
	color: black;
}

a img, img[useMap]
{
	border: none;
}

*, button
{
	outline: none;
}

a._img
{
	text-decoration: none;
}

*
{
	margin: 0;
	padding: 0;
}

body
{
	width: 700px;
	margin: auto;
	border: solid black 1px;
	
	font-family: Verdana, Arial, sans-serif;
}

body > *
{
	width: 100%;
}

body #header_a_container
{
	color: white;
	text-decoration:none;
}

header
{
	position: relative;
	height: 256px;
	
	background-position: center;
	background-image: url('images/header_background.png');
	background-repeat: no-repeat;
}

header img#swordsmen_white
{
	position: absolute;	
	top: 30px;
	right: 10px;
}

header h1
{
	color: white;
	font-family: 'papyrusregular';
	font-size: 3em;
	font-weight: normal;
	font-style: normal;
}

header h1 #first_part_title
{
	position: relative;
	left: 5px;
	display: inline-block;
	min-width: 500px;
}

header h1 #second_part_title
{
	position: relative;
	left: 80px;
	bottom: 45px;
}

header h1 #first_part_title_dynamic
{
	position: relative;
	left: 120px;
	display: inline-block;
	min-width: 500px;
}

header h1 #second_part_title_dynamic
{
	position: relative;
	left: 20px;
	bottom: 45px;
}

header h1 img
{
	width: 50%;
	position: relative;
	top: 0px;
	left: 40px;
}

#bodier
{
	display: inline-block;
	position: relative;
	
	background-position: top;
	background-image: url('images/header_gradient.png');
	background-repeat: no-repeat;
}

#bodier h1
{
	height: 42px;
	
	font-family: 'papyrusregular';
	font-size: 2em;
	font-weight: bold;
	font-style: normal;
	text-align: center;
}

<?php
echo '/* GENERATED BY PHP */
';
foreach ( $colorCodes as $color => $code ) {
	echo '#bodier h1.' . $color . '
{
	color: ' . $code . ';
}
';
}
?>

#bodier #right_container
{
	min-height: 100px;
	width: 515px;
	float: right;
	
	margin-right: 15px;
}

#bodier #right_container>*
{
	padding-right: 10px;
	padding-left: 55px;
}

#bodier #right_container #main_section
{
	padding-top: 40px;
	padding-bottom: 40px; /* MISE A JOUR */
	
	background-position: top;
	background-image: url('images/main_section_background.png');
	background-size: 100% 100%;
	background-repeat: no-repeat;
}

#bodier #right_container #main_section p
{
	text-align: justify;
}

#bodier #right_container #main_section p.accueil
{
	text-align: center;
}

#bodier #right_container #main_section p.accueil strong
{
	font-weight: normal;
	font-size: 1.5em;
}

#bodier #right_container #main_section img#derniere_minute
{
	float: left;
}


#bodier #right_container #part2 p
{
	text-align: center;
	font-weight: normal;
	font-size: 1.5em;
}

#bodier #right_container #part3
{
	padding: 0px;
	text-align: right;
}

#bodier #right_container #part3 a
{
	text-decoration: none;
}


#bodier #right_container #part3 div
{
	display: inline-block;
	vertical-align: bottom;
}

#bodier #right_container #part3 div:nth-child(2)
{
	height: 168px;
}

#bodier #right_container #part3 div h1
{
	text-align: center;
	font-family: 'papyrusregular';
	font-size: 1.4em;
	font-weight: bold;
}

#bodier #right_container #part3 p#quote
{
	width: 190px;
	height: 29px;
	padding: 45px 30px;
	
	background-position: top;
	background-image: url('images/quote_background.png');
	background-size: 100% 100%;
	background-repeat: no-repeat;
	
	font-weight: normal;
	font-size: 0.6em;
	text-align: center;
}

#bodier #right_container #part3 p#quote span
{
	font-weight: bold;
	font-size: 1em;
}

#bodier #right_container #part3 img#downloads
{
	width: 250px;
}

#bodier #right_container #main_section h1
{
	height: auto;
	
	font-size: 1.8em;
	text-align: left;
}

#bodier #right_container #main_section a.temoignages
{
	text-decoration: none;
}

#bodier #right_container #main_section a.temoignages p
{
	width: 350px;
	margin: 15px auto;
	padding: 0px 30px;
	
	background-position: center;
	background-image: url('images/temoignages_background.png');
	background-size: 100% auto;
	background-repeat: no-repeat;
	
	font-weight: normal;
	font-size: 0.8em;
	text-align: center;
}

#bodier #right_container #main_section a.temoignages p span
{
	font-weight: bold;
	font-size: 1.2em;
}

#bodier #right_container #main_section img.temoignages_sabre_orange
{
	display: block;
	margin: auto;
}

#bodier #right_container #main_section p.partenaires
{
	text-align: center;
	margin-top: 10px;
}

#bodier #right_container #main_section p.partenaires a
{
	font-style: italic;
	text-decoration: none;
}

#bodier #right_container #main_section p.partenaires a img
{
	vertical-align: middle;
}


#bodier #right_container #main_section.photos
{
	background-image: none;
	padding: 0;
	padding-top: 25px;
}

#bodier #right_container #main_section .arrow_vertical_container
{
	text-align: center;
	height: 23px;
}

#bodier #right_container #main_section .arrow_vertical_container button
{
	padding: 0;
	border: none;
	background-color: rgba(0, 0, 0, 0);
	cursor: pointer;
}

#bodier #right_container #main_section .arrow_vertical_container button img.arrow_vertical
{
	width: 150px;
}

#bodier #right_container #main_section p.arrow_vertical
{
	margin: auto;
}

#bodier #right_container #main_section.photos #photos_container
{
	text-align: center;
}

#bodier #right_container #main_section.photos #photos_container .column
{
	display: inline-block;
	vertical-align: top;
	width: 200px;
	height: 440px;
	margin: 20px 25px;
	
	background-position: center;
	background-image: url('images/photos_column_background.png');
	background-size: 100% 100%;
	background-repeat: no-repeat;
}

#bodier #right_container #main_section.photos #photos_container .column .photo_container
{
	width: 160px;
	height: 120px;
	
	margin: 0 auto;
	margin-top: 20px;
}

#bodier #right_container #main_section.photos #photos_container .column .photo_container a img.photo
{
	max-height: 120px;
	max-width: 160px;
	
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	-ms-border-radius: 5px;
	-o-border-radius: 5px;
	border-radius: 5px;
}

#bodier #right_container #main_section nav#first_nav .column
{
	display: inline-block;
	vertical-align: middle;
	width: 220px;
}

#bodier #right_container #main_section nav#first_nav .column a,
#bodier nav#nav_left a,
#bodier nav#nav_right a
{
	display: block;
	
	height: 60px;
	width: 170px;
	
	color: black;
	font-size: 1.2em;
	font-family: 'papyrusregular', sans-serif;
	font-weight: bold;
	font-style: normal;
	text-decoration: none;
}

#bodier #right_container #main_section nav#first_nav .column a.green,
#bodier nav#nav_left a.green,
#bodier nav#nav_right a.green
{
	background-position: bottom;
	background-image: url("images/nav_sabre_green.png");
	background-size: 90% 80%;
	background-repeat: no-repeat;
}

#bodier #right_container #main_section nav#first_nav .column a.blue
{
	background-position: bottom;
	background-image: url("images/nav_sabre_blue.png");
	background-size: 90% 80%;
	background-repeat: no-repeat;
}

#bodier nav#nav_right a.back_white
{
	text-align: right;
	
	background-position: bottom;
	background-image: url("images/nav_index_sabre_white.png");
	background-size: 90% 80%;
	background-repeat: no-repeat;
}

#bodier #right_container #main_section nav#first_nav .column a:hover,
#bodier nav#nav_left a:hover,
#bodier nav#nav_right a:hover
{
	background-image: url('images/nav_sabre_white.png');
}

#bodier nav#nav_right a:hover.back_white
{
	background-image: url('images/nav_index_sabre_white.png');
}

#bodier #right_container #main_section nav#first_nav .column a span
{
	margin-left: 50px;
}

#bodier nav#nav_left a span,
#bodier nav#nav_right a span
{
	margin-left: 50px;
}

#bodier nav#nav_right a.back_white span
{
	margin-left: 0px;
	margin-right: 45px;
}

#bodier #right_container #main_section nav#first_nav .column a span.too_long,
#bodier nav#nav_left a span.too_long,
#bodier nav#nav_right a span.too_long
{
	display: block;
	width: 120px;
	text-align: left;
	margin-left: 43px;
	margin-right: 0px;
}

#bodier #bodier_illustration_container
{
	text-align: center;
}

#bodier #bodier_illustration_container img#bodier_sabre_green
{
	width: 170px;
}

#bodier #bodier_illustration_container img#bodier_swordsmen_black
{
	position: relative;
	right: 50px;
}

#bodier div#reload_a
{
	position: absolute;
	top: -45px;
	left: 5px;
}

#bodier div#reload_a img#reload
{
	width: 130px;
}

#bodier nav#nav_left,
#bodier #section_center,
#bodier nav#nav_right
{
	display: inline-block;
	vertical-align: bottom;
}

#bodier #section_center
{
	min-height: 346px;
	width: 348px;
	margin-bottom: 20px;
}

#bodier #section_center #h1_resultats
{
	height: auto;
	
	background-position: center;
	background-image: url("images/title_sabre_black.png");
	background-repeat: no-repeat;
}

#bodier #right_container #main_section p a img.resto
{
	width: 130px;
}

#bodier #left_container
{
	/*min-height: 580px; MISE A JOUR */
	
	width: 170px;
	position: relative;
	padding-top: 8px;
}

#bodier #left_container nav#nav_main
{
	text-align: left;
}

#bodier #left_container nav#nav_main a
{
	display: block;
	
	height: 60px;
	width: 170px;
	
	color: black;
	font-size: 1.2em;
	font-family: 'papyrusregular', sans-serif;
	font-weight: bold;
	font-style: normal;
	text-decoration: none;
}

#bodier #left_container nav#nav_main a span
{
	margin-left: 50px;
}

#bodier #left_container nav#nav_main a span.too_long
{
	display: block;
	width: 120px;
	text-align: center;
	margin-left: 40px;
	margin-right: 0px;
}

<?php
echo '/* GENERATED BY PHP */
';
foreach ( $colorCodes as $color => $code ) {
	echo '#bodier #left_container nav#nav_main a.' . $color . '
{
	background-position: bottom;
	background-image: url("images/nav_sabre_' . $color . '.png");
	background-size: 90% 80%;
	background-repeat: no-repeat;
}
';
}
?>

#bodier #left_container nav#nav_main a:hover
{
	background-image: url('images/nav_sabre_white.png');
}

#bodier #left_container nav#nav_main a.index_white
{
	background-position: bottom;
	background-image: url("images/nav_index_sabre_white.png");
	background-size: 90% 80%;
	background-repeat: no-repeat;
}

#bodier #left_container nav#nav_main a:hover.index_white
{
	background-image: url('images/nav_index_sabre_white.png');
}

#bodier #left_container nav#nav_main a.youtube
{
	background-position: bottom;
	background-image: url("images/nav_sabre_youtube.png");
	background-size: 90% 80%;
	background-repeat: no-repeat;
}

#bodier #left_container nav#nav_main a:hover.youtube
{
	background-image: url('images/nav_sabre_youtube_play_.png');
}

#bodier #left_container nav#nav_main a.back_white
{
	text-align: right;
	
	background-position: bottom;
	background-image: url("images/nav_index_sabre_white.png");
	background-size: 90% 80%;
	background-repeat: no-repeat;
}

#bodier #left_container nav#nav_main a:hover.back_white
{
	background-image: url('images/nav_index_sabre_white.png');
}

#bodier #left_container nav#nav_main a.back_white span
{
	margin-left: 0px;
	margin-right: 45px;
}

<?php
echo '/* GENERATED BY PHP */
';
foreach ( $colorCodes as $color => $code ) {
	echo '#bodier #left_container nav#nav_main a:hover.' . $color . '
{
	color: ' . $code . ';
}
';
}
?>

#bodier #left_container p.encart
{
	background-position: top;
	background-image: url('images/encart_background.png');
	background-size: 100% 100%;
	background-repeat: no-repeat;
	
	margin-left: 15px;
	padding: 10px 0;
	text-align: center;
}

#bodier #left_container #arrow_max_container
{
	margin-top: 30px;
}

#bodier #left_container #arrow_max_container .button_max_container
{
	height: 45px;
	
	text-align: center;
}

#bodier #left_container #arrow_max_container .button_max_container button
{
	padding: 0;
	border: none;
	background-color: rgba(0, 0, 0, 0);
	cursor: pointer;
}

#bodier #left_container img#escrime_boucle
{
	/*position: absolute;
	bottom: 10px;*/
	
	width: 130px;
	display: block;
	margin-left: 20px;
	margin-right: 20px;
}

#sponsors
{
	display: inline-block;
}

#sponsors #sponsors_container
{
	margin: 5px auto;
	width: 635px;
}

#sponsors a img
{
	display: inline-block;
	vertical-align: middle;
}

footer
{
	min-height: 60px;
	
	background-image: url('images/header_background.png');
	background-size: 100% 100%;
	background-repeat: no-repeat;
}

footer nav#nav_footer
{
	text-align: center;
}

footer nav#nav_footer a
{
	display: inline-block;
	margin: 5px 13px;
	
	color: white;
	font-size: 1.2em;
	font-weight: normal;
	font-style: normal;
	text-decoration: none;
}

<?php
echo '/* GENERATED BY PHP */';
foreach ( $colorCodes as $color => $code ) {
	echo 'footer nav#nav_footer a.' . $color . ' span
{
	color: ' . $code . ';
}
';
}
?>

footer>p
{
	color: white;
	text-align: center;
	font-size: 0.7em;
}


